#!/bin/bash -e

################################################################################
# peers syncronisation git -> gw
################################################################################
# 1. Abholen der keys aus git
# 2. Rechte anpassen
# 3. ggf fastd keys neu einlesen
#
# cron job anlegen
# */15 * * * * /root/scripts/fastd-peers-update > /root/scripts/log/fastd-peers-update.log 2> /root/scripts/log/fastd-peers-update.err
################################################################################
#CHANGELOG
# V1.0 2014-01-07 little.ben
#   - Ersterstellung
# V1.1 2015-03-06 paalsteek
#   - Ordner über Variablen besser konfigurierbar
################################################################################

PEERSDIR="/etc/fastd/ffwp-mesh-vpn/peers/"
LOGDIR="/root/scripts/log/"

# in peers-Ordner wechseln
cd "${PEERSDIR}"

# git sync
git pull >"${LOGDIR}"/fastd-peers-update-pull.log 2>"${LOGDIR}"/fastd-peers-update-pull.err
#git pull

################################################################################

# Rechte und Besitzer aendern bei allen Dateien im peers-Ordner
# (ausser im Unterordner .git)
find -type f ! -path "*.git*" -exec chmod 664 {} \;
find -type f ! -path "*.git*" -exec chown :ffadm {} \;
cd ..

# Rechte und Besitzer des peers-Ordners ansich aendern
chown :ffadm peers/
chmod 755 peers/

################################################################################
# fastd keys neu einlesen, falls was geaendert wurde
S1=`cat "${LOGDIR}"/fastd-peers-update-pull.log`
S2='Already up-to-date.'

#http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-11.html
#http://stackoverflow.com/questions/2237080/how-to-compare-strings-in-bash-script

PID=`pidof fastd`

if [ "$S1" != "$S2" ];
then
        #/usr/bin/pkill -HUP fastd  #pkill geht nicht im cron
        kill -s HUP $PID
        logger "fastd keys neu eingelesen"
        #echo "fastd keys neu eingelesen"
fi

exit 0

